name: pkg_gov_uk_dashboards
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - flask-basicauth=0.2.0
  - dash=2.0
  - Werkzeug=2.0.3
  - pytest=6.2
  - pylint=2.12
  - black=22.3.0
  - numpy=1.22.0
  - pandas=1.3
  - plotly=5.5.0
  - dash-bootstrap-components=1.0.3
  - python-build=0.9.0