name: pkg_gov_uk_dashboards
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - dash=2.0
  - pytest=6.2
  - pylint=2.12
  - black=22.3.0
  - numpy=1.22.0
  - pandas=1.3
  - dash-bootstrap-components=1.0.3